version: '3.8'

services:
  ai-video-maker:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-3.5-turbo
      - MAX_VIDEO_DURATION=300
      - DEFAULT_VIDEO_RESOLUTION=1280x720
      - DEFAULT_TTS_PROVIDER=gtts
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
      - ./data:/app/data
      - ./assets:/app/assets
      - ./templates:/app/templates
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - ai-video-maker
    restart: unless-stopped

volumes:
  uploads:
  output:
  data:
  assets:
  templates:
  logs: